# Generated by Django 5.0.7 on 2024-08-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backup.customuser')),
            ],
        ),
    ]
