# Generated by Django 5.0.7 on 2024-09-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_scheduleddeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
