// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqRcZ4HapPFLjcNPL5ATSNg0rFBFjHaiA',
    appId: '1:895974675686:web:a8604fc481ad8c813d1727',
    messagingSenderId: '895974675686',
    projectId: 'trackexp-flutter',
    authDomain: 'trackexp-flutter.firebaseapp.com',
    storageBucket: 'trackexp-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7sC1YgbZ8-V5uOdRhPygYnMusGeq1qy0',
    appId: '1:895974675686:android:46a283e20c235a573d1727',
    messagingSenderId: '895974675686',
    projectId: 'trackexp-flutter',
    storageBucket: 'trackexp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu2U48zvM-xUYnWSy-ZINI2AYkAoFze58',
    appId: '1:895974675686:ios:63c646be66add3013d1727',
    messagingSenderId: '895974675686',
    projectId: 'trackexp-flutter',
    storageBucket: 'trackexp-flutter.appspot.com',
    iosBundleId: 'com.example.trackexp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu2U48zvM-xUYnWSy-ZINI2AYkAoFze58',
    appId: '1:895974675686:ios:63c646be66add3013d1727',
    messagingSenderId: '895974675686',
    projectId: 'trackexp-flutter',
    storageBucket: 'trackexp-flutter.appspot.com',
    iosBundleId: 'com.example.trackexp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqRcZ4HapPFLjcNPL5ATSNg0rFBFjHaiA',
    appId: '1:895974675686:web:6101c1d8dcd7c5fb3d1727',
    messagingSenderId: '895974675686',
    projectId: 'trackexp-flutter',
    authDomain: 'trackexp-flutter.firebaseapp.com',
    storageBucket: 'trackexp-flutter.appspot.com',
  );
}
